# Please do not store any SECURE INFORMATIONS in this file
# This file should be use for public info
theme:
  name: 'Jankx'
  short_name: 'Jankx'

plugins:
  woocommerce:
    required: true

layouts:
  container_width: 1200

images:
  thumbnail:
    width: 180
    height: 120
  medium:
    width: 480
    height: 350
  large:
    width: 1024
    height: 1024
mobile_images:
  medium:
    width: 520
    height: 380

colors:
  primary_color: "#A8201A"
  secondary: "#EC9A29"
  neutral: "#0F8B8D"
  secondary_contrast: "#143642",
  primary_contrast: "#DAD2D8"

version: "1.0.0"
