<?php

namespace Jankx\Gutenberg\Blocks;

use Jankx\Gutenberg\Block;
use Jankx\Layouts\DynamicDataLayout\Generators\TermTemplateBlockGenerator;

/**
 * Terms List block
 *
 * A lightweight clone of core/categories that renders every term of a chosen
 * taxonomy. Instead of a fixed <ul>/<select> markup the terms are looped
 * through the reusable jankx/dynamic-term-template block, so each item is
 * built from arbitrary inner blocks.
 *
 * Unlike DynamicTermLayoutBlock this block intentionally skips the layout
 * registry (grid/card/carousel/masonry), the AJAX filter endpoints and the
 * heading helper: it only queries terms and hands them to the term template
 * generator.
 *
 * @package Jankx\Gutenberg\Blocks
 * @since 2.0.0
 */
class TermListBlock extends Block
{
    protected $blockId = 'jankx/term-list';

    /** @var string[] Allowed layout values. */
    protected $allowedLayouts = ['list', 'grid', 'flex'];

    /** @var string[] Allowed orderby values. */
    protected $allowedOrderBy = ['name', 'slug', 'count', 'term_order', 'description'];

    /**
     * Render the block
     *
     * @param array $attributes Block attributes
     * @param string $content Block content
     * @param \WP_Block|null $block Block instance
     * @return string Rendered HTML
     */
    public function render($attributes, $content = '', $block = null)
    {
        $taxonomySlug = isset($attributes['taxonomy']) ? sanitize_key($attributes['taxonomy']) : '';

        if (empty($taxonomySlug) || !taxonomy_exists($taxonomySlug)) {
            return '';
        }

        $taxonomy = get_taxonomy($taxonomySlug);
        if (!$taxonomy) {
            return '';
        }

        $attributes = $this->normalizeAttributes($attributes);
        $layout = $attributes['layout'];

        $this->enqueueTemplateStyle();

        // The items wrapper generated by TermTemplateBlockGenerator already carries
        // --columns-desktop / columns-* for the grid layout, so the outer wrapper only
        // needs the layout modifier class.
        $wrapperAttributes = get_block_wrapper_attributes([
            'class' => 'jankx-term-list jankx-term-list--' . sanitize_html_class($layout),
        ]);

        $terms = $this->getTerms($attributes, $taxonomySlug);

        if (empty($terms) || is_wp_error($terms)) {
            return sprintf(
                '<div %s><div class="jankx-term-list__empty">%s</div></div>',
                $wrapperAttributes,
                esc_html($taxonomy->labels->no_terms)
            );
        }

        $templateBlock = $this->extractTemplateBlock(
            $block instanceof \WP_Block ? (isset($block->parsed_block) ? $block->parsed_block : []) : []
        );

        $generator = new TermTemplateBlockGenerator($templateBlock ?: [], $attributes);

        $html = $generator->generate($terms, array_merge($attributes, [
            'itemsWrapperClass' => 'jankx-term-list__items jankx-term-list__items--' . sanitize_html_class($layout),
            'itemClass' => 'jankx-term-list__item',
        ]));

        if (!is_string($html) || $html === '') {
            return sprintf(
                '<div %s><div class="jankx-term-list__empty">%s</div></div>',
                $wrapperAttributes,
                esc_html($taxonomy->labels->no_terms)
            );
        }

        return sprintf('<div %s>%s</div>', $wrapperAttributes, $html);
    }

    /**
     * Normalize and whitelist block attributes
     *
     * @param array $attributes Raw block attributes
     * @return array
     */
    protected function normalizeAttributes(array $attributes): array
    {
        $layout = isset($attributes['layout']) ? (string) $attributes['layout'] : 'list';
        if (!in_array($layout, $this->allowedLayouts, true)) {
            $layout = 'list';
        }

        $orderBy = isset($attributes['orderBy']) ? (string) $attributes['orderBy'] : 'name';
        if (!in_array($orderBy, $this->allowedOrderBy, true)) {
            $orderBy = 'name';
        }

        $order = isset($attributes['order']) ? strtoupper((string) $attributes['order']) : 'ASC';
        if (!in_array($order, ['ASC', 'DESC'], true)) {
            $order = 'ASC';
        }

        return array_merge($attributes, [
            'layout' => $layout,
            'orderBy' => $orderBy,
            'order' => $order,
            'postsPerPage' => max(0, (int) (isset($attributes['postsPerPage']) ? $attributes['postsPerPage'] : 0)),
            'columns' => max(1, (int) (isset($attributes['columns']) ? $attributes['columns'] : 3)),
            'hideEmpty' => !empty($attributes['hideEmpty']),
            'showOnlyTopLevel' => !empty($attributes['showOnlyTopLevel']),
            'showTermCount' => !empty($attributes['showTermCount']),
        ]);
    }

    /**
     * Run the term query
     *
     * @param array $attributes Normalized attributes
     * @param string $taxonomySlug Taxonomy slug
     * @return array|\WP_Error
     */
    protected function getTerms(array $attributes, string $taxonomySlug)
    {
        $args = [
            'taxonomy' => $taxonomySlug,
            'hide_empty' => !empty($attributes['hideEmpty']),
            'orderby' => $attributes['orderBy'],
            'order' => $attributes['order'],
        ];

        if (!empty($attributes['showOnlyTopLevel'])) {
            $args['parent'] = 0;
        }

        if ($attributes['postsPerPage'] > 0) {
            $args['number'] = $attributes['postsPerPage'];
        }

        $args = apply_filters('jankx/term-list/query_args', $args, $attributes);

        return get_terms($args);
    }

    /**
     * Recursively find the term template block inside the parsed block tree
     *
     * @param array $parsedBlock Parsed block data
     * @return array|null
     */
    protected function extractTemplateBlock(array $parsedBlock): ?array
    {
        if (empty($parsedBlock)) {
            return null;
        }

        if (($parsedBlock['blockName'] ?? '') === 'jankx/dynamic-term-template') {
            return $parsedBlock;
        }

        foreach (isset($parsedBlock['innerBlocks']) && is_array($parsedBlock['innerBlocks']) ? $parsedBlock['innerBlocks'] : [] as $inner) {
            $found = $this->extractTemplateBlock($inner);
            if ($found !== null) {
                return $found;
            }
        }

        return null;
    }

    /**
     * Enqueue the term template stylesheet (it holds the shared item markup CSS)
     *
     * The template block declares no "style" entry in its block.json, so it is
     * loaded manually here — the same way DynamicTermLayoutBlock does it.
     *
     * @return void
     */
    protected function enqueueTemplateStyle(): void
    {
        if (is_admin() || empty($this->blockPath)) {
            return;
        }

        $distBase = dirname($this->blockPath, 2) . '/dist';
        $stylePath = $distBase . '/blocks/dynamic-term-template/style.css';

        if (!file_exists($stylePath)) {
            return;
        }

        $handle = 'jankx-dynamic-term-template-style';

        if (wp_style_is($handle, 'registered')) {
            wp_enqueue_style($handle);
            return;
        }

        $assetPath = $distBase . '/blocks/dynamic-term-template/style.asset.php';
        $asset = file_exists($assetPath)
            ? require $assetPath
            : [
                'dependencies' => ['wp-block-library'],
                'version' => filemtime($stylePath),
            ];

        wp_enqueue_style(
            $handle,
            get_template_directory_uri() . '/resources/dist/blocks/dynamic-term-template/style.css',
            isset($asset['dependencies']) ? (array) $asset['dependencies'] : [],
            isset($asset['version']) ? $asset['version'] : null
        );
    }
}
