<?php

return [
    'corporate' => [
        'name' => 'Corporate',
        'description' => 'Professional corporate website with classic header, services showcase, and team section.',
        'preview' => 'https://jankx.com/previews/corporate.jpg',
        'thumbnail' => null,
        'tags' => ['business', 'corporate', 'professional'],
        'priority' => 10,
        'preset' => [
            'colors' => [
                'primary' => '#1e40af',
                'secondary' => '#0ea5e9',
                'link' => '#1e40af',
                'link_hover' => '#1e3a8a',
                'header_bg' => '#ffffff',
                'header_text' => '#1e293b',
                'footer_bg' => '#0f172a',
                'footer_text' => '#f8fafc',
                'button_bg' => '#1e40af',
                'button_text' => '#ffffff',
            ],
            'header' => 'classic',
            'typography' => [
                'body' => [
                    'font-family' => 'Inter, sans-serif',
                    'font-size' => '16',
                    'font-weight' => '400',
                    'line-height' => '1.6',
                    'color' => '#334155',
                ],
                'heading' => [
                    'font-family' => 'Plus Jakarta Sans, sans-serif',
                    'font-weight' => '700',
                    'color' => '#0f172a',
                ],
            ],
        ],
        'templates' => [
            'index.html' => 'index.html',
            'home.html' => 'home.html',
            'page.html' => 'page.html',
            'single.html' => 'single.html',
            'archive.html' => 'archive.html',
            'search.html' => 'search.html',
            '404.html' => '404.html',
        ],
        'template_parts' => [
            'header.html' => 'header.html',
            'footer.html' => 'footer.html',
            'sidebar.html' => 'sidebar.html',
        ],
        'theme_options' => [
            'container_width' => '1200',
            'sidebar_position' => 'right',
            'enable_sticky_header' => true,
            'sticky_header_trigger' => 'top',
            'header_type' => 'normal',
        ],
        'page_setup' => [
            'homepage' => 'home',
            'blog' => 'blog',
            'menu_location' => [
                'primary' => 'Main Menu',
            ],
        ],
        'required_plugins' => [],
        'required_extensions' => [],
    ],

    'magazine' => [
        'name' => 'Magazine',
        'description' => 'Modern news & magazine layout with featured posts, categories grid, and newsletter signup.',
        'preview' => 'https://jankx.com/previews/magazine.jpg',
        'thumbnail' => null,
        'tags' => ['magazine', 'news', 'blog', 'content'],
        'priority' => 20,
        'preset' => [
            'colors' => [
                'primary' => '#dc2626',
                'secondary' => '#f59e0b',
                'link' => '#dc2626',
                'link_hover' => '#b91c1c',
                'header_bg' => '#ffffff',
                'header_text' => '#111827',
                'footer_bg' => '#111827',
                'footer_text' => '#f3f4f6',
                'button_bg' => '#dc2626',
                'button_text' => '#ffffff',
            ],
            'header' => 'topbar',
            'typography' => [
                'body' => [
                    'font-family' => 'Merriweather, serif',
                    'font-size' => '17',
                    'font-weight' => '400',
                    'line-height' => '1.7',
                    'color' => '#1f2937',
                ],
                'heading' => [
                    'font-family' => 'Inter, sans-serif',
                    'font-weight' => '800',
                    'color' => '#111827',
                ],
            ],
        ],
        'templates' => [
            'index.html' => 'index.html',
            'home.html' => 'home-magazine.html',
            'page.html' => 'page.html',
            'single.html' => 'single-magazine.html',
            'archive.html' => 'archive-magazine.html',
            'category.html' => 'category.html',
            'tag.html' => 'tag.html',
            'search.html' => 'search.html',
            '404.html' => '404.html',
        ],
        'template_parts' => [
            'header.html' => 'header-topbar.html',
            'footer.html' => 'footer.html',
            'sidebar.html' => 'sidebar-right.html',
        ],
        'theme_options' => [
            'container_width' => '1200',
            'sidebar_position' => 'right',
            'enable_sticky_header' => true,
            'sticky_header_trigger' => 'hero',
            'header_type' => 'normal',
        ],
        'page_setup' => [
            'homepage' => 'home-magazine',
            'blog' => 'blog',
            'menu_location' => [
                'primary' => 'Primary Menu',
                'secondary' => 'Top Bar Menu',
            ],
        ],
        'required_plugins' => [],
        'required_extensions' => [],
    ],

    'creative' => [
        'name' => 'Creative Portfolio',
        'description' => 'Bold portfolio for designers, photographers, and creative agencies with full-screen visuals.',
        'preview' => 'https://jankx.com/previews/creative.jpg',
        'thumbnail' => null,
        'tags' => ['portfolio', 'creative', 'agency', 'minimal'],
        'priority' => 30,
        'preset' => [
            'colors' => [
                'primary' => '#7c3aed',
                'secondary' => '#ec4899',
                'link' => '#7c3aed',
                'link_hover' => '#6d28d9',
                'header_bg' => 'transparent',
                'header_text' => '#ffffff',
                'footer_bg' => '#0f172a',
                'footer_text' => '#f8fafc',
                'button_bg' => '#7c3aed',
                'button_text' => '#ffffff',
            ],
            'header' => 'centered',
            'typography' => [
                'body' => [
                    'font-family' => 'Inter, sans-serif',
                    'font-size' => '16',
                    'font-weight' => '400',
                    'line-height' => '1.6',
                    'color' => '#334155',
                ],
                'heading' => [
                    'font-family' => 'Plus Jakarta Sans, sans-serif',
                    'font-weight' => '700',
                    'color' => '#0f172a',
                ],
            ],
        ],
        'templates' => [
            'index.html' => 'index.html',
            'home.html' => 'home-portfolio.html',
            'page.html' => 'page.html',
            'single.html' => 'single.html',
            'archive.html' => 'archive.html',
            'search.html' => 'search.html',
            '404.html' => '404.html',
        ],
        'template_parts' => [
            'header.html' => 'header-centered.html',
            'footer.html' => 'footer-minimal.html',
        ],
        'theme_options' => [
            'container_width' => '1200',
            'sidebar_position' => 'right',
            'enable_sticky_header' => true,
            'sticky_header_trigger' => 'first_group',
            'header_type' => 'overlay',
        ],
        'page_setup' => [
            'homepage' => 'home',
            'blog' => 'blog',
            'menu_location' => [
                'primary' => 'Main Menu',
            ],
        ],
        'required_plugins' => [],
        'required_extensions' => [],
    ],

    'landing' => [
        'name' => 'Landing Page',
        'description' => 'High-conversion landing page with hero section, features, testimonials, and CTA.',
        'preview' => 'https://jankx.com/previews/landing.jpg',
        'thumbnail' => null,
        'tags' => ['landing', 'marketing', 'saas', 'startup'],
        'priority' => 40,
        'preset' => [
            'colors' => [
                'primary' => '#059669',
                'secondary' => '#10b981',
                'link' => '#059669',
                'link_hover' => '#047857',
                'header_bg' => '#ffffff',
                'header_text' => '#1e293b',
                'footer_bg' => '#0f172a',
                'footer_text' => '#f8fafc',
                'button_bg' => '#059669',
                'button_text' => '#ffffff',
            ],
            'header' => 'split',
            'typography' => [
                'body' => [
                    'font-family' => 'Inter, sans-serif',
                    'font-size' => '16',
                    'font-weight' => '400',
                    'line-height' => '1.6',
                    'color' => '#334155',
                ],
                'heading' => [
                    'font-family' => 'Plus Jakarta Sans, sans-serif',
                    'font-weight' => '800',
                    'color' => '#0f172a',
                ],
            ],
        ],
        'templates' => [
            'index.html' => 'index.html',
            'home.html' => 'home-landing.html',
            'page.html' => 'page.html',
            'single.html' => 'single.html',
            'archive.html' => 'archive.html',
            'search.html' => 'search.html',
            '404.html' => '404.html',
        ],
        'template_parts' => [
            'header.html' => 'header-split.html',
            'footer.html' => 'footer.html',
        ],
        'theme_options' => [
            'container_width' => '1200',
            'sidebar_position' => 'right',
            'enable_sticky_header' => true,
            'sticky_header_trigger' => 'hero',
            'header_type' => 'normal',
        ],
        'page_setup' => [
            'homepage' => 'home',
            'blog' => 'blog',
            'menu_location' => [
                'primary' => 'Main Menu',
            ],
        ],
        'required_plugins' => [],
        'required_extensions' => [],
    ],
];
