import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import PlanPrice from './';
export const Default = () => {
    return (_jsxs("div", { children: [_jsx("h3", { children: "Plan with standard price" }), _jsx(PlanPrice, { rawPrice: 99.8 }), _jsx("br", {}), _jsx("h3", { children: "Plan with a price range" }), _jsx(PlanPrice, { rawPrice: [99.99, 139.99] }), _jsx("br", {}), _jsx("h3", { children: "Plan with a price of '0'" }), _jsx(PlanPrice, { rawPrice: 0 }), _jsx("br", {}), _jsx("h3", { children: "Plan with discounted price" }), _jsxs("div", { style: { display: 'flex' }, children: [_jsx(PlanPrice, { rawPrice: 8.25, original: true }), _jsx(PlanPrice, { rawPrice: 2, discounted: true })] }), _jsx("br", {}), _jsx("h3", { children: "Plan with discounted price range" }), _jsxs("div", { style: { display: 'flex' }, children: [_jsx(PlanPrice, { rawPrice: [8.25, 20.23], original: true }), _jsx(PlanPrice, { rawPrice: [2.25, 3], discounted: true })] }), _jsx("br", {}), _jsx("h3", { children: "Plan with discounted price and tax" }), _jsxs("div", { style: { display: 'flex' }, children: [_jsx(PlanPrice, { rawPrice: 8.25, original: true, taxText: "10%" }), _jsx(PlanPrice, { rawPrice: 2, discounted: true, taxText: "10%" })] }), _jsx("br", {}), _jsx("h3", { children: "Plan with discounted price range and tax" }), _jsxs("div", { style: { display: 'flex' }, children: [_jsx(PlanPrice, { rawPrice: [8.25, 20.23], original: true, taxText: "10%" }), _jsx(PlanPrice, { rawPrice: [2.25, 3], discounted: true, taxText: "10%" })] }), _jsx("br", {}), _jsx("h3", { children: "Simple View (isInSignup) - Plan with discounted price and tax " }), _jsxs("div", { style: { display: 'flex' }, children: [_jsx(PlanPrice, { rawPrice: 8.25, original: true, taxText: "10%", isInSignup: true }), _jsx(PlanPrice, { rawPrice: 2, discounted: true, taxText: "10%", isInSignup: true })] }), _jsx("br", {}), _jsx("h3", { children: "Simple View (isInSignup) - Plan with discounted price range and tax " }), _jsxs("div", { style: { display: 'flex' }, children: [_jsx(PlanPrice, { rawPrice: [8.25, 20.23], original: true, taxText: "10%", isInSignup: true }), _jsx(PlanPrice, { rawPrice: [2.25, 3], discounted: true, taxText: "10%", isInSignup: true })] })] }));
};
export default {
    title: 'Unaudited/PlanPrice',
    component: PlanPrice,
};
//# sourceMappingURL=index.stories.js.map