<?php

/**
 * Integration test to compare PHP and JavaScript render output
 * 
 * This test ensures that the HTML structure generated by PHP's getHtmlStructure()
 * can be used by JavaScript to render the same output as PHP's render() method.
 */

namespace Tests\Integration\PostLayout;

use Tests\Helpers\TestCase;
use Tests\Helpers\HtmlAssertions;
use Jankx\Layouts\PostLayout\PostLayoutManager;
use Jankx\Layouts\PostLayout\Supports\GridLayout;
use Jankx\Layouts\PostLayout\Supports\ListLayout;
use Jankx\Gutenberg\Blocks\PostTypeLayoutBlock;
use WP_Query;

class PostLayoutPhpJsComparisonTest extends TestCase
{
    use HtmlAssertions;

    protected $layoutManager;
    protected $block;

    protected function setUp(): void
    {
        parent::setUp();
        $this->layoutManager = PostLayoutManager::getInstance();
        
        // Provide block path for PostTypeLayoutBlock
        $blockPath = dirname(__DIR__, 3) . '/resources/blocks/post-type-layout';
        $this->block = new PostTypeLayoutBlock($blockPath);
    }

    /**
     * Test that structure from getHtmlStructure() contains all necessary information
     * to render the same HTML as PHP's render() method
     */
    public function testGridLayoutStructureContainsAllRenderInfo()
    {
        $layout = new GridLayout();
        $layout->setOptions([
            'columns' => 3,
            'columnsTablet' => 2,
            'columnsMobile' => 1,
            'thumbnailPosition' => 'top',
            'showFeaturedImage' => true,
            'showTitle' => true,
            'showDate' => true,
            'showAuthor' => false,
            'showExcerpt' => true,
        ]);

        $structure = $layout->getHtmlStructure();

        // Verify structure contains all necessary info for rendering
        $this->assertArrayHasKey('container', $structure);
        $this->assertArrayHasKey('itemWrapper', $structure);
        $this->assertArrayHasKey('emptyState', $structure);

        // Container should have correct tag and classes
        $container = $structure['container'];
        $this->assertEquals('ul', $container['tag']);
        $this->assertContains('post-type-layout-grid', $container['classes']);
        $this->assertContains('columns-3', $container['classes']);

        // Item wrapper should have correct tag and classes
        $itemWrapper = $structure['itemWrapper'];
        $this->assertEquals('li', $itemWrapper['tag']);
        $this->assertContains('post-item', $itemWrapper['classes']);
        $this->assertContains('thumbnail-position-top', $itemWrapper['classes']);
        $this->assertContains('has-thumbnail', $itemWrapper['classes']);
    }

    /**
     * Test that structure can be serialized to JSON for JavaScript
     */
    public function testStructureIsJsonSerializable()
    {
        $layout = new GridLayout();
        $layout->setOptions(['columns' => 3]);

        $structure = $layout->getHtmlStructure();

        // Should be JSON serializable
        $json = json_encode($structure, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        $this->assertNotFalse($json, 'Structure should be JSON serializable');

        // Should decode back to same structure
        $decoded = json_decode($json, true);
        $this->assertIsArray($decoded);
        $this->assertEquals('grid', $decoded['layout']);
        $this->assertArrayHasKey('container', $decoded);
        $this->assertArrayHasKey('itemWrapper', $decoded);
    }

    /**
     * Test that PostTypeLayoutBlock localizes correct structure
     */
    public function testPostTypeLayoutBlockLocalizesCorrectStructure()
    {
        $reflection = new \ReflectionClass(PostTypeLayoutBlock::class);
        $method = $reflection->getMethod('getLayoutStructures');
        $method->setAccessible(true);

        $structures = $method->invoke($this->block);

        // Should have layouts and postItem
        $this->assertArrayHasKey('layouts', $structures);
        $this->assertArrayHasKey('postItem', $structures);

        // Should have grid layout
        $this->assertArrayHasKey('grid', $structures['layouts']);
        $gridStructure = $structures['layouts']['grid'];

        // Verify grid structure
        $this->assertEquals('grid', $gridStructure['layout']);
        $this->assertEquals('ul', $gridStructure['container']['tag']);
        $this->assertEquals('li', $gridStructure['itemWrapper']['tag']);

        // Should have list layout
        $this->assertArrayHasKey('list', $structures['layouts']);
        $listStructure = $structures['layouts']['list'];

        // Verify list structure
        $this->assertEquals('list', $listStructure['layout']);
        $this->assertEquals('div', $listStructure['container']['tag']);
        $this->assertEquals('article', $listStructure['itemWrapper']['tag']);

        // Post item structure should be complete
        $postItem = $structures['postItem'];
        $this->assertArrayHasKey('featuredImage', $postItem);
        $this->assertArrayHasKey('title', $postItem);
        $this->assertArrayHasKey('date', $postItem);
        $this->assertArrayHasKey('author', $postItem);
        $this->assertArrayHasKey('metaWrapper', $postItem);
        $this->assertArrayHasKey('excerpt', $postItem);
        $this->assertArrayHasKey('contentWrapper', $postItem);
    }

    /**
     * Test that structure matches expected PHP render output classes
     */
    public function testStructureMatchesPhpRenderClasses()
    {
        $layout = new GridLayout();
        $layout->setOptions([
            'columns' => 3,
            'thumbnailPosition' => 'top',
            'showFeaturedImage' => true,
        ]);

        $structure = $layout->getHtmlStructure();

        // Container classes should match renderDefault output
        $containerClasses = $structure['container']['classes'];
        $this->assertContains('post-type-layout-grid', $containerClasses);
        $this->assertContains('columns-3', $containerClasses);

        // Item wrapper classes should match renderPostItem output
        $itemClasses = $structure['itemWrapper']['classes'];
        $this->assertContains('post-item', $itemClasses);
        $this->assertContains('thumbnail-position-top', $itemClasses);
        $this->assertContains('has-thumbnail', $itemClasses);
    }

    /**
     * Test that different thumbnail positions produce different structures
     */
    public function testThumbnailPositionAffectsStructure()
    {
        $layoutTop = new GridLayout();
        $layoutTop->setOptions([
            'thumbnailPosition' => 'top',
            'showFeaturedImage' => true,
        ]);

        $layoutLeft = new GridLayout();
        $layoutLeft->setOptions([
            'thumbnailPosition' => 'left',
            'showFeaturedImage' => true,
        ]);

        $structureTop = $layoutTop->getHtmlStructure();
        $structureLeft = $layoutLeft->getHtmlStructure();

        // Both should have thumbnail-position class but different values
        $this->assertContains('thumbnail-position-top', $structureTop['itemWrapper']['classes']);
        $this->assertContains('thumbnail-position-left', $structureLeft['itemWrapper']['classes']);
    }

    /**
     * Test that showFeaturedImage affects has-thumbnail class
     */
    public function testShowFeaturedImageAffectsThumbnailClass()
    {
        $layoutWithThumb = new GridLayout();
        $layoutWithThumb->setOptions([
            'showFeaturedImage' => true,
        ]);

        $layoutWithoutThumb = new GridLayout();
        $layoutWithoutThumb->setOptions([
            'showFeaturedImage' => false,
        ]);

        $structureWith = $layoutWithThumb->getHtmlStructure();
        $structureWithout = $layoutWithoutThumb->getHtmlStructure();

        $this->assertContains('has-thumbnail', $structureWith['itemWrapper']['classes']);
        $this->assertContains('no-thumbnail', $structureWithout['itemWrapper']['classes']);
    }

    /**
     * Test that structure includes CSS variables for responsive columns
     */
    public function testStructureIncludesCssVariables()
    {
        $layout = new GridLayout();
        $layout->setOptions([
            'columns' => 3,
            'columnsTablet' => 2,
            'columnsMobile' => 1,
        ]);

        $structure = $layout->getHtmlStructure();
        $styles = $structure['container']['styles'];

        $this->assertArrayHasKey('--columns-desktop', $styles);
        $this->assertArrayHasKey('--columns-tablet', $styles);
        $this->assertArrayHasKey('--columns-mobile', $styles);

        $this->assertEquals('3', $styles['--columns-desktop']);
        $this->assertEquals('2', $styles['--columns-tablet']);
        $this->assertEquals('1', $styles['--columns-mobile']);
    }

    /**
     * Test that structure includes data attributes
     */
    public function testStructureIncludesDataAttributes()
    {
        $layout = new GridLayout();
        $structure = $layout->getHtmlStructure();

        $containerAttrs = $structure['container']['attributes'];
        $this->assertArrayHasKey('data-layout', $containerAttrs);
        $this->assertEquals('grid', $containerAttrs['data-layout']);

        $itemAttrs = $structure['itemWrapper']['attributes'];
        $this->assertArrayHasKey('id', $itemAttrs);
        $this->assertStringContainsString('post-', $itemAttrs['id']);
    }

    /**
     * Test that all registered layouts have valid structures
     */
    public function testAllRegisteredLayoutsHaveValidStructures()
    {
        $layouts = $this->layoutManager->getLayouts(['field' => 'all']);
        $reflection = new \ReflectionClass(PostTypeLayoutBlock::class);
        $method = $reflection->getMethod('getLayoutStructures');
        $method->setAccessible(true);

        $structures = $method->invoke($this->block);

        foreach ($layouts as $layoutInfo) {
            $layoutName = $layoutInfo['name'] ?? '';
            if (empty($layoutName)) {
                continue;
            }

            // Should have structure in localized data
            $this->assertArrayHasKey(
                $layoutName,
                $structures['layouts'],
                "Layout {$layoutName} should have structure in localized data"
            );

            $structure = $structures['layouts'][$layoutName];

            // Structure should be valid
            $this->assertIsArray($structure, "Layout {$layoutName} structure should be array");
            $this->assertArrayHasKey('layout', $structure);
            $this->assertArrayHasKey('container', $structure);
            $this->assertArrayHasKey('itemWrapper', $structure);
            $this->assertEquals($layoutName, $structure['layout']);

            // Should be JSON serializable
            $json = json_encode($structure);
            $this->assertNotFalse($json, "Layout {$layoutName} structure should be JSON serializable");
        }
    }
}
