<?php

/**
 * Integration test to compare PHP and JavaScript render output
 * 
 * This test ensures that the HTML structure generated by PHP's getHtmlStructure()
 * can be used by JavaScript to render the same output as PHP's render() method.
 */

namespace Tests\Integration\PostLayout;

use Tests\Helpers\TestCase;
use Tests\Helpers\HtmlAssertions;
use Jankx\Layouts\DynamicDataLayout\BlockTemplateLayoutManager;
use Jankx\Layouts\DynamicDataLayout\BlockLayouts\GridLayout;
use Jankx\Layouts\DynamicDataLayout\BlockLayouts\ListLayout;
use Jankx\Layouts\DynamicDataLayout\BlockLayouts\CarouselLayout;
use Jankx\Gutenberg\Blocks\DynamicDataLayoutBlock;
use WP_Query;

class PostLayoutPhpJsComparisonTest extends TestCase
{
    use HtmlAssertions;

    protected $layoutManager;
    protected $block;

    protected function setUp(): void
    {
        parent::setUp();
        $this->layoutManager = BlockTemplateLayoutManager::getInstance();
        
        // Provide block path for DynamicDataLayoutBlock
        $blockPath = dirname(__DIR__, 3) . '/resources/blocks/dynamic-data-layout';
        $this->block = new DynamicDataLayoutBlock($blockPath);
    }

    /**
     * Test that structure from getHtmlStructure() contains all necessary information
     * to render the same HTML as PHP's render() method
     */
    public function testGridLayoutStructureContainsAllRenderInfo()
    {
        $layout = new GridLayout();
        $layout->setOptions([
            'columns' => 3,
            'columnsTablet' => 2,
            'columnsMobile' => 1,
            'thumbnailPosition' => 'top',
            'showFeaturedImage' => true,
            'showTitle' => true,
            'showDate' => true,
            'showAuthor' => false,
            'showExcerpt' => true,
        ]);

        $structure = $layout->getHtmlStructure();

        // Verify structure contains all necessary info for rendering
        $this->assertArrayHasKey('container', $structure);
        $this->assertArrayHasKey('itemWrapper', $structure);
        $this->assertArrayHasKey('emptyState', $structure);

        // Container should have correct tag and classes
        $container = $structure['container'];
        $this->assertEquals('ul', $container['tag']);
        $this->assertContains('post-type-layout-grid', $container['classes']);
        $this->assertContains('columns-3', $container['classes']);

        // Item wrapper should have correct tag and classes
        $itemWrapper = $structure['itemWrapper'];
        $this->assertEquals('li', $itemWrapper['tag']);
        $this->assertContains('post-item', $itemWrapper['classes']);
        $this->assertContains('thumbnail-position-top', $itemWrapper['classes']);
        $this->assertContains('has-thumbnail', $itemWrapper['classes']);
    }

    /**
     * Test that structure can be serialized to JSON for JavaScript
     */
    public function testStructureIsJsonSerializable()
    {
        $layout = new GridLayout();
        $layout->setOptions(['columns' => 3]);

        $structure = $layout->getHtmlStructure();

        // Should be JSON serializable
        $json = json_encode($structure, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        $this->assertNotFalse($json, 'Structure should be JSON serializable');

        // Should decode back to same structure
        $decoded = json_decode($json, true);
        $this->assertIsArray($decoded);
        $this->assertEquals('grid', $decoded['layout']);
        $this->assertArrayHasKey('container', $decoded);
        $this->assertArrayHasKey('itemWrapper', $decoded);
    }

    /**
     * Test that DynamicDataLayoutBlock localizes correct structure
     */
    public function testDynamicDataLayoutBlockLocalizesCorrectStructure()
    {
        $reflection = new \ReflectionClass(DynamicDataLayoutBlock::class);
        $method = $reflection->getMethod('getLayoutStructures');
        $method->setAccessible(true);

        $structures = $method->invoke($this->block);

        // Should have layouts and postItem
        $this->assertArrayHasKey('layouts', $structures);
        $this->assertArrayHasKey('postItem', $structures);

        // Should have common_grid layout
        $this->assertArrayHasKey('common_grid', $structures['layouts']);
        $gridStructure = $structures['layouts']['common_grid'];

        // Verify grid structure
        $this->assertEquals('grid', $gridStructure['layout']);
        $this->assertEquals('ul', $gridStructure['container']['tag']);
        $this->assertEquals('li', $gridStructure['itemWrapper']['tag']);

        // Should have common_list layout
        $this->assertArrayHasKey('common_list', $structures['layouts']);
        $listStructure = $structures['layouts']['common_list'];

        // Verify list structure
        $this->assertEquals('list', $listStructure['layout']);
        $this->assertEquals('div', $listStructure['container']['tag']);
        $this->assertEquals('article', $listStructure['itemWrapper']['tag']);

        // Should have common_carousel layout
        $this->assertArrayHasKey('common_carousel', $structures['layouts']);
        $carouselStructure = $structures['layouts']['common_carousel'];

        // Verify carousel structure
        $this->assertEquals('carousel', $carouselStructure['layout']);
        $this->assertEquals('div', $carouselStructure['container']['tag']);
        $this->assertContains('dynamic-data-layout--carousel', $carouselStructure['container']['classes']);
    }

    /**
     * Test that structure matches expected PHP render output classes
     */
    public function testStructureMatchesPhpRenderClasses()
    {
        $layout = new GridLayout();
        $layout->setOptions([
            'columns' => 3,
            'thumbnailPosition' => 'top',
            'showFeaturedImage' => true,
        ]);

        $structure = $layout->getHtmlStructure();

        // Container classes should match renderDefault output
        $containerClasses = $structure['container']['classes'];
        $this->assertContains('post-type-layout-grid', $containerClasses);
        $this->assertContains('columns-3', $containerClasses);

        // Item wrapper classes should match renderPostItem output
        $itemClasses = $structure['itemWrapper']['classes'];
        $this->assertContains('post-item', $itemClasses);
        $this->assertContains('thumbnail-position-top', $itemClasses);
        $this->assertContains('has-thumbnail', $itemClasses);
    }

    /**
     * Test that different thumbnail positions produce different structures
     */
    public function testThumbnailPositionAffectsStructure()
    {
        $layoutTop = new GridLayout();
        $layoutTop->setOptions([
            'thumbnailPosition' => 'top',
            'showFeaturedImage' => true,
        ]);

        $layoutLeft = new GridLayout();
        $layoutLeft->setOptions([
            'thumbnailPosition' => 'left',
            'showFeaturedImage' => true,
        ]);

        $structureTop = $layoutTop->getHtmlStructure();
        $structureLeft = $layoutLeft->getHtmlStructure();

        // Both should have thumbnail-position class but different values
        $this->assertContains('thumbnail-position-top', $structureTop['itemWrapper']['classes']);
        $this->assertContains('thumbnail-position-left', $structureLeft['itemWrapper']['classes']);
    }

    /**
     * Test that showFeaturedImage affects has-thumbnail class
     */
    public function testShowFeaturedImageAffectsThumbnailClass()
    {
        $layoutWithThumb = new GridLayout();
        $layoutWithThumb->setOptions([
            'showFeaturedImage' => true,
        ]);

        $layoutWithoutThumb = new GridLayout();
        $layoutWithoutThumb->setOptions([
            'showFeaturedImage' => false,
        ]);

        $structureWith = $layoutWithThumb->getHtmlStructure();
        $structureWithout = $layoutWithoutThumb->getHtmlStructure();

        $this->assertContains('has-thumbnail', $structureWith['itemWrapper']['classes']);
        $this->assertContains('no-thumbnail', $structureWithout['itemWrapper']['classes']);
    }

    /**
     * Test that structure includes CSS variables for responsive columns
     */
    public function testStructureIncludesCssVariables()
    {
        $layout = new GridLayout();
        $layout->setOptions([
            'columns' => 3,
            'columnsTablet' => 2,
            'columnsMobile' => 1,
        ]);

        $structure = $layout->getHtmlStructure();
        $styles = $structure['container']['styles'];

        $this->assertArrayHasKey('--columns-desktop', $styles);
        $this->assertArrayHasKey('--columns-tablet', $styles);
        $this->assertArrayHasKey('--columns-mobile', $styles);

        $this->assertEquals('3', $styles['--columns-desktop']);
        $this->assertEquals('2', $styles['--columns-tablet']);
        $this->assertEquals('1', $styles['--columns-mobile']);
    }

    /**
     * Test that structure includes data attributes
     */
    public function testStructureIncludesDataAttributes()
    {
        $layout = new GridLayout();
        $structure = $layout->getHtmlStructure();

        $containerAttrs = $structure['container']['attributes'];
        $this->assertArrayHasKey('data-layout', $containerAttrs);
        $this->assertEquals('grid', $containerAttrs['data-layout']);

        $itemAttrs = $structure['itemWrapper']['attributes'];
        $this->assertArrayHasKey('id', $itemAttrs);
        $this->assertStringContainsString('post-', $itemAttrs['id']);
    }

    /**
     * Test that all registered layouts have valid structures
     */
    public function testAllRegisteredLayoutsHaveValidStructures()
    {
        $layouts = $this->layoutManager->getCommonLayouts();
        $reflection = new \ReflectionClass(DynamicDataLayoutBlock::class);
        $method = $reflection->getMethod('getLayoutStructures');
        $method->setAccessible(true);

        $structures = $method->invoke($this->block);

        $layoutStructures = $structures['layouts'] ?? [];
        foreach ($layoutStructures as $key => $structure) {
            $this->assertIsArray($structure, "Structure for '{$key}' should be an array");
            $this->assertArrayHasKey('container', $structure, "Structure for '{$key}' should have 'container'");
            $this->assertArrayHasKey('itemWrapper', $structure, "Structure for '{$key}' should have 'itemWrapper'");
        }
        
        $this->assertGreaterThan(0, count($layoutStructures));

        foreach ($layouts as $layoutInfo) {
            $layoutName = $layoutInfo['name'] ?? '';
            if (empty($layoutName)) {
                continue;
            }

            $key = "common_{$layoutName}";
            // Should have structure in localized data
            $this->assertArrayHasKey(
                $key,
                $structures['layouts'],
                "Layout {$layoutName} should have structure in localized data"
            );

            $structure = $structures['layouts'][$key];

            // Structure should be valid
            $this->assertIsArray($structure, "Layout {$layoutName} structure should be array");
            $this->assertArrayHasKey('layout', $structure);
            $this->assertArrayHasKey('container', $structure);
            $this->assertArrayHasKey('itemWrapper', $structure);
            $this->assertEquals($layoutName, $structure['layout']);

            // Should be JSON serializable
            $json = json_encode($structure);
            $this->assertNotFalse($json, "Layout {$layoutName} structure should be JSON serializable");
        }
    }

    /**
     * Test that CarouselLayout structure includes all Embla carousel options
     */
    public function testCarouselLayoutIncludesAllEmblaOptions()
    {
        $layout = new CarouselLayout();
        $layout->setOptions([
            'columns' => 4,
            'slidesToScroll' => 2,
            'loop' => true,
            'autoplay' => true,
            'autoplayDelay' => 5000,
            'carouselAlign' => 'center',
            'carouselAxis' => 'x',
            'carouselDirection' => 'ltr',
            'carouselStartIndex' => 1,
            'carouselDuration' => 50,
            'carouselDragFree' => true,
            'carouselDragThreshold' => 15,
            'carouselSkipSnaps' => true,
            'carouselContainScroll' => 'keepSnaps',
            'carouselInViewThreshold' => 0.5,
        ]);

        $structure = $layout->getHtmlStructure();
        $container = $structure['container'];
        $attributes = $container['attributes'];

        // Verify all Embla options are present in data attributes
        $this->assertArrayHasKey('data-embla-carousel', $attributes);
        $this->assertArrayHasKey('data-align', $attributes);
        $this->assertArrayHasKey('data-axis', $attributes);
        $this->assertArrayHasKey('data-direction', $attributes);
        $this->assertArrayHasKey('data-start-index', $attributes);
        $this->assertArrayHasKey('data-duration', $attributes);
        $this->assertArrayHasKey('data-drag-threshold', $attributes);
        $this->assertArrayHasKey('data-contain-scroll', $attributes);
        $this->assertArrayHasKey('data-in-view-threshold', $attributes);
        $this->assertArrayHasKey('data-loop', $attributes);
        $this->assertArrayHasKey('data-autoplay', $attributes);
        $this->assertArrayHasKey('data-autoplay-delay', $attributes);
        $this->assertArrayHasKey('data-drag-free', $attributes);
        $this->assertArrayHasKey('data-skip-snaps', $attributes);

        // Verify values
        $this->assertEquals('center', $attributes['data-align']);
        $this->assertEquals('x', $attributes['data-axis']);
        $this->assertEquals('ltr', $attributes['data-direction']);
        $this->assertEquals('1', $attributes['data-start-index']);
        $this->assertEquals('50', $attributes['data-duration']);
        $this->assertEquals('15', $attributes['data-drag-threshold']);
        $this->assertEquals('keepSnaps', $attributes['data-contain-scroll']);
        $this->assertEquals('0.5', $attributes['data-in-view-threshold']);
        $this->assertEquals('true', $attributes['data-loop']);
        $this->assertEquals('true', $attributes['data-autoplay']);
        $this->assertEquals('5000', $attributes['data-autoplay-delay']);
        $this->assertEquals('true', $attributes['data-drag-free']);
        $this->assertEquals('true', $attributes['data-skip-snaps']);
    }

    /**
     * Test that CarouselLayout structure has correct nested viewport/container structure
     */
    public function testCarouselLayoutNestedStructure()
    {
        $layout = new CarouselLayout();
        $layout->setOptions(['columns' => 3]);

        $structure = $layout->getHtmlStructure();
        $container = $structure['container'];

        // Should have nested children: viewport -> container
        $this->assertArrayHasKey('children', $container);
        $this->assertCount(1, $container['children']);

        $viewport = $container['children'][0];
        $this->assertEquals('div', $viewport['tag']);
        $this->assertContains('embla__viewport', $viewport['classes']);
        $this->assertArrayHasKey('children', $viewport);
        $this->assertCount(1, $viewport['children']);

        $emblaContainer = $viewport['children'][0];
        $this->assertEquals('div', $emblaContainer['tag']);
        $this->assertContains('embla__container', $emblaContainer['classes']);
    }
}
