<?php
/**
 * Editor script asset file
 *
 * This file is automatically generated by WordPress build process
 * For now, we'll provide a basic structure
 */

return [
    'dependencies' => [
        'wp-blocks',
        'wp-dom-ready',
        'wp-edit-post',
        'wp-components',
        'wp-media-utils',
        'wp-i18n',
        'wp-element',
        'wp-data',
        'wp-compose',
    ],
    'version' => \Jankx\Jankx::getFrameworkVersion(),
];
